# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13MeGF_HpdPiplvNR3nvkrIZQvHgPULgZ
"""

import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
count = 4

for a in range(1,-1,-1):
  for b in range(1,-1,-1):
    if count%2 == 0:
      print("x"*(count)+str(np.flipud(arr[a,b])))
    else:
      print("x"*(count)+str(arr[a,b]))
    count -= 1

import numpy as np
from numpy import random

x = random.randint(100,size=(5,5))

for a in range(5):
  print(np.sort(x[a]))

dic = {
    "name" : "mon",
    "age" : 17,
    "gender" : "male",
    "food" : "steak"
}

# li_dic = []

# for i in dic:
#   li_dic.append(dic[i])

# for i in range(len(li_dic),0,-1):
#   print(li_dic[i-1])

for i in dic:
  print(i, dic[i])

dic = {
    "product" : ["fan", "Tv", "lamp", "computer"],
    "price" : [200, 500, 100, 700],
    "quantity" : [2, 3, 1, 4]
}

for a in dic:
  print(a, end=" ")
  for b in dic[a]:
    print(b, end=" ")
  print()

dic = {
    "name" : {
        "khem" : "khem",
        "van" : "van",
        "stang" : "stang"
    },
    "age" : {
        "khem" : 18,
        "van" : 25,
        "stang" : 16
    }
}

for a in dic:
  for b in dic[a]:
    print(dic[a][b])

import pandas as pd
import numpy as np

arr = np.array([0,1,2,3,4,5,6,7])
ls = [1,2,3,4,5,6,7,8]
dic = {
    "name" : "khem",
    "age" : 18,
    "gender" : "male"
}
dic["name"] = "mon"

df = pd.Series(dic)

print(df.loc["name"], df["age"])

import pandas as pd
import numpy as np

dic = {
    "product" : ["fan", "Tv", "lamp", "computer"],
    "price" : [200, 500, 100, 700],
    "quantity" : [2, 3, 1, 4]
}

# for a in dic:
#   x = dic[a]
#   x.pop(1)

for a in dic["product"]:
  if a == "Tv":
    continue
  print(a, end=" ")
print()

price = pd.Series(dic["price"])
quan = pd.Series(dic["quantity"])
sum = 0

for a in range(len(price)):
  if a == 1:
    continue
  sum += price[a]*quan[a]
  print(price[a]*quan[a], end=" ")
print()

print(sum)

import pandas as pd
import numpy as np

dic = {
    "product" : ["fan", "Tv", "lamp", "computer", "ps5", "iphone"],
    "price" : [200, 500, 100, 700, 20000, 30000],
    "quantity" : [18, 25, 1, 9, 20, 6],
    "sum" : [0, 0, 0, 0, 0, 0]
}

df = pd.DataFrame(dic)

for i in range(len(df)):
  dic["sum"][i] = df.loc[i][1]*df.loc[i][2]
  if df.loc[i][2] < 10:
    continue
  print(df.loc[i][1]*df.loc[i][2])

print(pd.DataFrame(dic))

import pandas as pd

df = pd.read_csv("data.csv")
# df2 = pd.DataFrame(df[df["Duration"] > 150])

dic = {
    "Duration" : [],
    "Pulse" : [],
    "Maxpulse" : [],
    "Calories" : [],
}

for i in range(len(df["Maxpulse"])):
  if df["Maxpulse"][i] - df["Pulse"][i] > 10:
    for j in df:
      dic[j].append(df[j][i])

print(pd.DataFrame(dic))
# print(pd.DataFrame(dic).to_string())

import pandas as pd

df = pd.read_csv("data.csv")
# df.fillna(0, inplace=True)
sum = 0

for i in df["Calories"]:
  if i-i == 0:
    sum += i
  
print(sum)

import pandas as pd

df = pd.read_csv("data.csv")

for i in df.keys():
  for j in range(len(df)):
    if df.loc[j,i]%2 == 1:
      df.loc[j,i] = 0

print(df)

import pandas as pd

df = pd.read_csv("data2.csv")
date = []

for i in df.index:
  if date.count(df["Date"][i]) == 0:
    date.append(df["Date"][i])
  else:
    print(df.loc[i])

import pandas as pd

df = pd.read_csv("data-firearm.csv")
df.fillna(0, inplace=True)
state = []
gun = {}
permit = {}
months_gun = {}
most = "Alabama"
ala_gun = 0

for i in df.index:
  if df["state"].duplicated()[i] == False:
    state.append(df["state"][i])
  else:
    continue

# for i in state:
#   x = 0
#   for j in df.index:
#     if df["state"][j] == i:
#       x += df["handgun"][j]
#       x += df["long_gun"][j]
#       x += df["other"][j]
#   gun.update({i : x})

# for i in gun:
#   if gun[i] > gun[most]:
#     most = i
#   else:
#     continue

# for i in state:
#   per = 0
#   per_re = 0
#   for j in df.index:
#     if df["state"][j] == i:
#       per += df["permit"][j]
#       per_re += df["permit_recheck"][j]
#   if per - per_re < 0:
#     x = 0
#   else:
#     x = per - per_re
#   permit.update({i : x})

# for i in df.index:
#   if df["state"][i] == "Alabama":
#     if int(df["month"][i][:4]) - 2018 >= 0:
#       ala_gun += df["handgun"][i]

for i in state:
  months = []
  for j in df.index:
    if df["state"][j] == i:
      if months.count(df["month"][j][5:]) == 0:
        months.append(df["month"][j][5:])
      else:
        continue
  months.sort()
  months = dict.fromkeys(months, 0)
  for j in months:
    x = 0
    for k in df.index:
      if df["state"][k] == i:
        if df["month"][k][5:] == j:
          x += df["handgun"][k]
          x += df["long_gun"][k]
          x += df["other"][k]
    months[j] = x
  months_gun[i] = months
print(pd.DataFrame(months_gun))

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

df = pd.read_csv("data2.csv")
duration = []
count = []

for i in df.index:
  if df["Duration"].duplicated()[i] == False:
    duration.append(str(df["Duration"][i]))

for i in duration:
  x = 0
  for j in df.index:
    if df["Duration"][j] == int(i):
      x += 1
  count.append(x)
  
plt.bar(duration, count)
plt.show

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

df = pd.read_csv("data-firearm.csv")
df.fillna(0, inplace=True)
state = []
year = []
gun = []

for i in df.index:
  if df["state"].duplicated()[i] == False:
    state.append(df["state"][i])
  else:
    continue

for i in df.index:
  if year.count(df["month"][i][:4]) == 0:
    year.append(df["month"][i][:4])

for i in state:
  gun.clear()
  for j in year:
    x = 0
    y = 0
    for k in df.index:
      if df["state"][k] == i and df["month"][k][:4] == j:
        x += df["handgun"][k]
        x += df["long_gun"][k]
        x += df["other"][k]
        if df["handgun"][k] > 0:
          y += 1
        if df["long_gun"][k] > 0:
          y += 1
        if df["other"][k] > 0:
          y += 1
    gun.append(x/y)
  plt.figure(figsize=(25,4))
  plt.plot(year, gun)
  plt.title(i)
  plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("steam.csv")
platform = {}
year = {}

for i in range(1):
  x = []
  y = []

  for j in df.index:
    if df["platforms"].duplicated()[j] == False:
      x.append(df["platforms"][j])
      y.append(1)
    else:
      y[x.index(df["platforms"][j])] += 1

  for j in range(len(x)):
    platform.update({x[j]:y[j]})

for i in range(1):
  x = []
  y = []

  for i in df.index:
    if x.count(df["release_date"][i][:4]) == 0:
      x.append(df["release_date"][i][:4])
  x.sort()

  for i in x:
    count = 0
    for j in df["release_date"]:
      if j[:4] == i:
        count += 1
    y.append(count)
  
  for i in range(len(x)):
    year.update({x[i]:y[i]})

plt.pie(list(platform.values()), labels=list(platform.keys()))
plt.title("Platforms Charts")
plt.show()

plt.figure(figsize=(25,5))
plt.bar(list(year.keys()), list(year.values()))
plt.title("Year Statistics")
plt.show()